@startuml
autonumber

    actor User as u

    participant "Wallet Unit" as w
    participant "RP Instance" as v

    u->w: Open the Wallet Instance
    activate w
    u<->w: User authentication by the Wallet Instance or by a WSCA

    u->w: User selects the proximity presentation functionality
    opt Mandatory if Step 2 is not performed by WSCA
    w<->u: User authentication by WSCA
    end

    w->w: Generate new ephemeral key pair \n(""EDeviceKey.Priv"", ""EDeviceKey.Pub"")

    rnote over w,v #LIGHTGREEN
    <b>A)</b> ""DeviceEngagement"" data exchange over QR code or NFC
    endrnote

    activate v

    v->v: Generate new ephemeral key pair \n(""EReaderKey.Priv"", ""EReaderKey.Pub"")
    v->v: Compute session key

    v->v: Prepare encrypted ""DeviceRequest"" with \nper-""DocRequest"" ""readerAuth""

    rnote over w,v #LIGHTGREEN
    <b>B)</b> ""SessionEstablishment"" carries ""EReaderKey.Pub"" and \nencrypted ""DeviceRequest"" over BLE or NFC
    endrnote


    w->w: Compute session key
    w->w: Decrypt ""SessionEstablishment"" and ""DeviceRequest""
    w->w: Validate every ""readerAuth"" and select one Trust Anchor path
    alt EUDIW path
        w->w: EUDIW Authentication and Authorization; validate scope and EDP
    else National Trust Framework path
        w->w: Relying Party Proximity Authentication and Authorization; validate scope
    end

    w-->u: Show validated RP/Service, purpose, requested Credentials/attributes, \nretention and privacy-policy information
    u->w: Approval

    rnote over w,v #LIGHTGREEN
    <b>C)</b> Send a signed and encrypted response (""SessionData"") 
    with requested attributes over a BLE or NFC secure channel
    endrnote

    v->v: Decrypt ""SessionData"" and independently validate \ndevice/issuer authentication, digests, validity and status

    w<->v: Session Termination
    deactivate v
    deactivate w
@enduml
