@startuml
autonumber

participant "Authentic Source" as as
participant "Credential Issuer" as i

as -> i : Credential Offer object Request (authenticSourceId, datasetId, objectId)

rnote over i #LightGreen
  Checks
endrnote

i -> i : generate Credential Offer object

i -> as : Credential Offer object Response (Credential Offer object)
@enduml