@startuml Wallet Unit Attestation Issuance
autonumber
hide footbox

'Participants
actor "User" as user
participant "Wallet Instance" as app 
participant "Key Attestation APIs" as kats #springgreen
participant "Device Integrity Service APIs" as aats #springgreen
participant "Wallet Provider backend" as bck

user->app: Request a new operation that\nrequires a Wallet Unit Attestation
activate app

app->app: Check if Cryptographic Hardware Key \nTag (""hardware_key_tag""), Key Attestation API, and Device Integrity APIs are available

app->app: Generates an ephemeral key pair (""ephemeral_key_pub"", ""ephemeral_key_priv"")

rnote over app,bck #LIGHTGREEN
Check Wallet Provider is part of the Federation and obtain its metadata
endrnote

app->bck: Request ""nonce""
activate bck

bck->bck: Generate ""nonce""

bck-->app: ""nonce""
deactivate bck


app->app: Generate ""client_data_hash"" as SHA256(""nonce"", ""ephemeral_key_pub"")

app->app: Generate Cryptographic Hardware Key PoP\n""hardware_signature"" = sign((""client_data_hash"", ""hardware_key_tag""), ""hardware_key_priv"")

alt if Android

activate kats

app->kats: ""client_data_hash""

kats->kats: Generate ""key_attestation""\nbound to nonce

kats-->app: ""key_attestation"" 
deactivate kats

app->app: Generate Wallet Unit Attestation Request with ""key_assertion"", ""hardware_signature"", ""nonce"",\n""hardware_key_tag"", ""ephemeral_key_pub"" signed with ephemeral ""ephemeral_key_priv""

else if iOS

app->aats: ""client_data_hash""
aats->aats: Generate ""integrity_assertion""\nbound to nonce
aats-->app: ""integrity_assertion""
app->app: Generate Wallet Unit Attestation Request with ""integrity_assertion"", ""hardware_signature"", ""nonce"",\n""hardware_key_tag"", ""ephemeral_key_pub"" signed with ephemeral ""ephemeral_key_priv""
end


app->bck: Send Wallet Unit Attestation Request
activate bck


bck->bck: Validate ""nonce""

alt if Android
bck->bck: Validate ""key_attestation""
else if iOS
bck->bck: Validate ""integrity_assertion""
end
bck->bck: Validate ""hardware_signature""
bck->bck: Validate ""ephemeral_key_pub"" PoP
bck->bck: Create Wallet Unit Attestation


bck-->app: Wallet Unit Attestation Response

deactivate bck
deactivate app




@enduml