@startuml

[*] --> Unreg
    
state "UNREGISTERED" as Unreg
Unreg : Baseline state. \nOutside the trust boundary.

state "REGISTERED" as Reg
Reg :  Identity established. \nEcosystem access granted.

state "OPERATIONAL" as Op
Op : Fully authorized. 

state "REMOVED" as Withdrawn
Withdrawn : Forward operations rejected. \nHistorical operations may be validated.
    
Unreg --> Reg : Onboarding & Identity Verification
Reg --> Op : Issuance of Trust Artifacts
Op --> Reg : Trust Artifacts expired \nor revoked due to Entity updates
Reg --> Withdrawn : Registration revocation
Op --> Withdrawn : Critical Failure / Offboarding \n(Trust Artifact revocation)
Withdrawn --> [*] : Terminal State

@enduml